





```{r}
library(spotifyr)
Sys.setenv(SPOTIFY_CLIENT_ID = 'xxxxxxxxxxxxxxxxxxxxxxxxxx')
Sys.setenv(SPOTIFY_CLIENT_SECRET = 'xxxxxxxxxxxxxxxxxxxx')

access_token <- get_spotify_access_token()

```




```{r}
david_bowie <- get_artist_audio_features('david bowie')

```







```{r}


library(dplyr)
library(purrr)
library(knitr)

# Artist Keys, We see David Bowie's most of songs major
david_bowie %>% 
    count(key_mode, sort = TRUE) %>% 
    head(5) %>% 
    kable()

```






```{r}
# recently what i listen
library(lubridate)

get_my_recently_played(limit = 10) %>% 
    mutate(
        artist.name = map_chr(track.artists, function(x) x$name[1]),
        played_at = as_datetime(played_at)
        ) %>% 
    select(
      all_of(c("track.name", "artist.name", "track.album.name", "played_at"))
      ) %>% 
    kable()

```




```{r}
# artists and their genres
get_my_top_artists_or_tracks(type = 'artists', 
                             time_range = 'long_term', 
                             limit = 10) %>% 
    select(.data$name, .data$genres) %>% 
    rowwise %>% 
    mutate(genres = paste(.data$genres, collapse = ', ')) %>% 
    ungroup %>% 
    kable()
```






```{r}
# my top artists and their tracks (long term)
get_my_top_artists_or_tracks(type = 'tracks', 
                             time_range = 'long_term', 
                             limit = 10) %>% 
    mutate(
        artist.name = map_chr(artists, function(x) x$name[1])
        ) %>% 
    select(name, artist.name, album.name) %>% 
    kable()
```






```{r}

joy <- get_artist_audio_features('coldplay')
```






```{r}

library(ggplot2)
library(ggridges)

ggplot(
    joy, 
    aes(x = valence, y = album_name)
    ) + 
geom_density_ridges() + 
theme_ridges() +
labs(title = "Joyplot of Coldplay's joy distributions", 
     subtitle = "Based on valence pulled from Spotify's Web API with spotifyr")
```







```{r}

get_my_playlists(limit = "5")

```




```{r}

get_my_followed_artists(
  limit = 20,
  after = NULL,
  authorization = get_spotify_authorization_code(),
  include_meta_info = FALSE
)

```

